- hosts: all
  become: true
  tasks:
      - name: create new deplpoyment
        command: kubectl apply -f /home/ubuntu/Deployment.yaml
      - name: create new service
        command: kubectl apply -f /home/ubuntu/Service.yaml
