- hosts: all
  become: true
  tasks:
      - name: create new deplpoyment
        command: kubectl apply -f Deployment.yaml
      - name: create new service
        command: kubectl apply -f Service.yaml
